baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'Unified Federal Technologies'

google_analytics_id: null
homepage:
  show_call_box: true
logo:
  mobile: "images/logo-mobile.svg"
  desktop: "images/logo.png"
  desktop_height: "30px"
footer:
  copyright_text: 'Copyright 2020 Unified Federal Technologies LLC'

seo:
  meta_og_title: "Unified Federal Technologies"
  meta_og_type: "website"
  meta_og_url: "http://unifiedfederal.com"
  meta_og_image: "https://raw.githubusercontent.com/zerostaticthemes/jekyll-serif-theme/master/screenshots/tn.png"
  meta_og_description: "Unified Federal is an economically disadvantaged women-owned small business (WSOB) in the software consulting and information technology space based in the Detroit, MI area."
  meta_twitter_card: "summary"
  meta_twitter_site: "@unifiedfederal"
  meta_twitter_creator: "@unifiedfederal"

collections:
  services:
    output: true
    permalink: /services/:path/

defaults:
  - scope:
      type: services
    values:
      layout: service
      bodyClass: page-services-single
  - scope:
      path: 'images'
    values:
      image: true

sass:
  style: compact # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables
